### ISSUE TITLE
Function Update: Tagging Stability and Minimizing User Changes (User and Developer Input Desired)

### ISSUE THREAD

**Issue by sigrunixia** [carlonicora/obsidian-rpg-manager#160]
## Scope
Core-System. Changes a functional part of the plugin itself.

## Summary
RPGM speed and stability is built on its ability to assign components to tags. Tags are a static object that do not change in response to variables without user input. However, as tags can be changed currently by the user via feature, via user by Obsidian option, and via plugins such as Tag Wrangler, there has been a consistent issue with users experiencing notes breaking due to tags either not updating correctly, being customized, or being updated via external applications. 

In order to begin to transition RPGM to a highly stable core-system upon which customized modules can be built to interface to it, such as a D&D Worldbuilding interface, or the most awesome SWN table randomizer ever, negating measures are needed. Some are being worked on right now, whereas others are in the planning and discussion stages, such as this one. 

### Goal
The overall goal is to create as much friction as possible to changing the tag away from its set defaults, but still leave it as an "option" if the user wants to convert the note away from RPGM.

## Proposed Solution
Tags for now still seems to remain an ideal system. 

My initial proposed solution utilizing tags is the following:
1. Insert only one YAML tag into a note of RPGM.
2. RPGM runs the normal check on the notes, and determines that any note with RPGM as a tag, is a note it should take action on.
3. RPGM then runs a secondary check (if tag: RPGM, then...) on a specialized callout or code block that is placed on the bottom of the note when it is first made into a RPGM note. This callout or code block then contains the component tags needed for RPGM to process the dynamic code blocks.

### Possible Effects
This could slow down loading times, by an unknown amount. The larger the vault, the longer the loading times. 
There is also a bit more screen real estate that is taken up at the bottom of the note. 

### Kudos Given
This idea of placing the data at the bottom was originally inspired by [DB Folder](https://github.com/RafaelGB/obsidian-db-folder) which offers the same functionality for its inline inquiries (Though the team is still working on adding it to [be read in a callout box](https://github.com/RafaelGB/obsidian-db-folder/issues/419#issue-1384251776) by allowing inlines to be added below each other automatically, no matter where they are).

## Next Steps
This is an ongoing discussion and nothing is set in stone. Feedback and suggestions are appreciated.

**Comment by carlonicora** [comment]
@sigrunixia I have sent you a beta version containing this. Would love to hear your thoughts.

To test it, better to start with a `v2.0` vault and upgrade to the version I sent.

**Comment by sigrunixia** [comment]
Upgrade from 2.0 to 3.0 With new system went well. 
[obsidian.md-1665498070285.log](https://github.com/carlonicora/obsidian-rpg-manager/files/9756929/obsidian.md-1665498070285.log)

## On Tags
- Tags that are not correctly linked to other tags pre-upgrade will remain incorrectly linked post-upgrade. This is expected behavior and system warns of need to correct tags.
- However, correcting tags is no longer intuitive. Would we be able to "regenerate" or "reassign" a new ID/tag without entirely refilling the note with new component blocks?

## Unexpected Behavior
- Somehow, unrelated non-rpm files got converted to RPGM files. "Wyrmskull Throne", "Ruinstone", and "Draakhorn". 
[Wyrmskull Throne.md](https://github.com/carlonicora/obsidian-rpg-manager/files/9757028/Wyrmskull.Throne.md)
[Ruinstone.md](https://github.com/carlonicora/obsidian-rpg-manager/files/9757031/Ruinstone.md)
[Draakhorn.md](https://github.com/carlonicora/obsidian-rpg-manager/files/9757034/Draakhorn.md)


## Suggestion
Within the RPGManager Codeblock, include the following in the generated code-block.
```RpgManagerID
**Do not edit below unless instructed to**
id: 8-0-1/4/4/1
checksum: 233589786dcaac4e5a258be2eb47a6dc
```

**Comment by carlonicora** [comment]
Thanks @sigrunixia 

A few comments:
- It is strange that tags that are not correctly linked fails... either the naming convention is completely different, or there is a bug somewhere in the system #166

A few actionable tasks for me:
- Correcting tags: I need to create a new modal form to allow users to fix the issues in the ID visually #163 
- The tag-guessing should convert only tags that have `rpgm` anywhere in the tag, and skip the rest #165
- Adding the **DO NOT EDIT**, yes, to be done! #164

I will also analyse the error log to find out what broke and I will send you something after the other tasks have been completed.

Thanks for the report

**Comment by carlonicora** [comment]
## Bug Fix Report

- [x] Files without tags which can be linked to RPGM are not seen as a `component` during the update #166 and #165 
- [x] New modal to correct the IDs #163 
- [x] Added the DO NOT EDIT message in the ID codeblock #164 

### Bonus

- [x] If an ID is changed manually, RPGM refuses to accept it

### Next Steps

We need a new round of testing to see if all the bugs have been removed. In my testing things go rather smoothly. I am missing perspective, though

### What can be made better

At the moment, if there are many errors, they have to be fixed one by one in specific order. A bit tedious, but not a show-stopper.

**Comment by sigrunixia** [comment]
As far as everything in my vault and the files accessible to me, the fixes have done their job and everything works flawlessly. No odd tags getting picked up. The renaming of ID's works fine and I trigged itAs a plus, we got a "move component" button out of the whole thing!
