### ISSUE TITLE
Add modal form to correct component ID

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#163]
Now that the `component ID` is stored in the `RpgManagerID` code block, there is the need of a modal form to correct any mistake.

**Comment by carlonicora** [comment]
## Modal Form Usage

The modal for to update or fix the ID of a component should be triggered in two places:
1. Error Reporting
2. In the component itself, allowing the user to move the component in different campaigns/adventures/acts

| Location | Behaviour |
|---|---|
| Error Reporting | Instead of focussing on the frontmatter of the note itself, the link should open the modal form to update the ID of the `component`|
| Component | A link named `move this {componenttype}` or `fix the hierarchy of this {componenttype}` should be available in the `component`|

### General behaviour of the Modal Form

In general, the modal should show the relevant hierarchical options for a specific `component`, allowing the user to pick the correct hierarchical parents.
In case of duplicated IDs (_for example, two scenes with the same id_), the modal should propose the new id, that the user could edit (_but not duplicating an existing id_)

**Comment by carlonicora** [comment]
## Tasks

- [x] Create Modal
- [x] Update Modal to support hierarchical structure
- [x] Create modal launcher from sidebar
- [ ] Create modal launcher from breadcrumb
- [ ] Fix UI
