### ISSUE TITLE
Redesign Documentation

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#168]
## Scope

The current documentation has been poorly written, and both its design and its presentation could benefit from a complete overhaul.

### Proposed Changes

I propose either to move the documentation entirely on GitHub Wiki, or to redesign it using a better style/template

**Comment by sigrunixia** [comment]
## Initial Discovery
- [ ] Determine the pros and cons of leaving documentation in existing format, versus GitHub Wiki. Tentative Completion Date 2022-10-14.

## Discovery Results
| Current | Wiki Page |
|:---:|:---:|
|TBD|TBD|

## Next Steps
To be plotted with results of discovery.

**Comment by sigrunixia** [comment]
## Tasks - Taken from Discord Questions
 - [ ] Describe how to get image attachments to work from inside the vault on PC and NPC pages, both automatically and manually.

**Comment by carlonicora** [comment]
## Images functionality

RPG Manager has two ways of showing a main image for a component
1. Reading directly from an online resource
2. Reading a file from the Obsidian `Attachment` folder

This is done transparently, reading the `data.image` metadata in each `component`.

The two are mutually exclusive, with a valid url in the `data.image` field having the priority over a local image

### Online Image

If the `data.image` metadata in the `RpgManagerData` code block is set to a value **different** from `null`, `""` or empty, RPG Manager will use the url to display the image.

#### Edge case for online image

If the url is not correct, or the image is not available any longer, RPG Manager does not display the image, and a standaard HTML error is displayed in the console

### Local Image File

If the `data.image` metadata in the `RpgManagerData` code block **is set** to a value of `null`, `""` or empty, RPG Manager will try and locate an image with the same name as the file `basename` in the `Attachment` folder.

If no image match the criteria, RPG Manager will not display the image.

**Comment by sigrunixia** [comment]
A follow up to the image documentation and a possible split needed for a Feature. Tagging the questions as tasks just in case tickets are needed. 
- [ ] Does RPGM currently perform recursive searching of the attachments folder (will it look in subfolders of attachments)? 
- [ ] Additionally, is it case sensitive on the folder name and file name?
- [ ] What would be the realistic difficulty in adding the customization of where RPGM looks for images in what folder be, similar to how it looks for templates? 

#### Use Case
For a use case example to questions 1 and 3, a LOT of people in the Tabletop-games discord channel use z_assets or similar naming to store all their images, due to the way folders display in obsidian. Some also categorize their images in subfolders. 

Furthermore, I could very easily see this being mentioned as a downside by Mr. Plunkett in his future review video if this functionality was not added. However, if it was already vetted and explained on the outset as: 
"I have looked into this and it was found in testing that it would slow down RPGM to an unusable status in large vaults. The best I can do within the limitations of Obsidian right now is a compromise of this, and have you name the image the same as the file in a set folder. I have also added the ability for you to link to the image directly from within the file. You can also link to external images as well."

**Comment by carlonicora** [comment]
In answer to your question:
1. Not currently. Fairly easy to implement
2. Not currently. Fairly easy to implement
3. Doable

If you assign me three new issues for the three updates, I will make them work tomorrow as 3.0.2

Thanks for the insight!

**Comment by sigrunixia** [comment]
I don't think we'd want case sensitivity (and the problems that would come with it). If there currently was, I was going to suggest we fix it to be not case sensitive. 

I'll make tickets for the other two. :)

**Comment by sigrunixia** [comment]
As of today. Beginning to load updated documentation into Wiki after Carlo and I discussed how it is likely better to do so now.

**Comment by sigrunixia** [comment]
I am closing this as I think we have the non-technical documentation settled. It will be appropriate to open a new issue for API-Documentation/Technical Documentation.
