### ISSUE TITLE
Note Taking

### ISSUE THREAD

**Issue by carlonicora** [carlonicora/obsidian-rpg-manager#175]
## Scope

Design a way of collecting notes during the running of a session that are linked, at the same time, to a session and a scene

### Introduction

The note-taking during the running of sessions is still very weak. It relies upon writing notes, but the notes are not easily reachable after the session.
Moreover, there is no real link between a note and a scene, as the session keeps the notes in a non-analysable way

### Ideal solution

Generate a centralise place where to store notes during the running of the session. The notes should contain:

- Relationship to the session
- Relationship to the scene
- Date and time
- Storyteller's feedback on the scene design
- Storyteller's feedback on related `components`
- Association to a `todo` list

### Next Steps

- [x] Determine the priority for this
- [x] Prepare a better requirement analysis
- [x] Estimate development time

**Comment by carlonicora** [comment]
## Requirements

#170 must be implemented

## Additional information

The implementation of this feature would solve #124

**Comment by sigrunixia** [comment]
I've been mulling on this one since I have read it. My non-coder brain has come up with a hack-way of doing this. Maybe it will help you think of a proper way to do this. This assumes scenes and sessions are the only 2 files you are concerned with. 

1. Scenes and sessions get creation date, creation time, modified date, modified time
2. The most recent recently created scene, and most recently created session, receives an additional tag or id. Instead of ending in 11 or 12, it ends in 11a or 12a. When one is created after that, RPGM removes the a from the prior scene.
3. Normally when RPGM starts and initializes, and does its normal day-to-day stuff, nothing changes. If a session note is opened and logged, nothing changes. If a scene note is opened and logged, ditto. If both are open and logged.. also ditto.
4. However if a session note is opened, and a scene note is opened, and a new scrap note is open, then some new stuff happens.
5. Scrap note upon open checks tags and looks for most recently created 11a and 12a. It then checks to see if modified 11a and 12a is later. If yes, it auto links.
6. When a person hits enter in the scrap note, it runs that check again. If it detects a change in links, it asks if it should link the new notes. (maybe a new scene?)
7. Finally, it checks when the note is closed. 

Super kludgy and more intensive, and probably not doable.

**Comment by carlonicora** [comment]
Hello hello!!

Thanks for the feedback. I think there is a better and cleaner way of doing it. For a some time I wanted to add a `feedback` session on a scene, to tell me how this scene went and why.

I am envisioning something like this:

- When you are in a Session, you see a button titled `Add new note/comment`
- A modal opens, with the name of the session and a selector for the scene the note/comment refers to
  - If an active timer is running, the scene the timer is running on will be automatically selected
- In the modal you will find a text area where to leave a comment (Related to #170 )
- In the modal you will also find a series of optional elements to give feedback (thumbs up/down, a dropdown to select the `quality` of a scene - _I still need to think this through_ -)
- When you save the note/comment, it is displayed automatically in the session and in the scene

Ideally, everything is going to be transparent for the user

**Comment by carlonicora** [comment]
## User Story

### Add notes to Scene
<**As a**> Storyteller
<**I want to**> Add a textual note on the scene when it's played
<**So that**> I can write what went on in the specific scene

### See notes in scene list
<**As a**> Storyteller
<**I want to**> See the notes in the list of scenes
<**So that**> I can see immediately what went on in each scene

### Analyse scene plot success
<**As a**> Storyteller
<**I want to**> Be able to mark if a scene went as plotted and give a reason
<**So that**> In future scenes plotting I can be supported in writing a better scene and avoiding past mistakes

### Analyse scene quality
<**As a**> Storyteller
<**I want to**> Be able to score the quality of a scene and give a reason
<**So that**> In future scene plotting I can be supported in writing better scenes

### Scene Rose
<**As a**> Storyteller
<**I want to**> Award a rose to a specific player character 
<**So that**> I can see which player character played the best game in a session

### Add Action Verb to Scene
<**As a**> Storyteller
<**I want to**> add a verb that defines the player characters' expected actions in a scene
<**So that**> I can associate a verb to the analyser and get better support during the analysis phase

## Tasks
- [ ] Add notes to Scene
- [ ] See notes in scene list
- [ ] Add Action Verb to Scene
- [ ] Analyse scene plot success
- [ ] Analyse scene quality
- [ ] Scene Rose
